print ("EXAMPLE 1")
name = input ("What is your name? ")
print (f"Hello {name} and welcome to CT8")
print ("Today we will tell a story with your help")
print ("")
print ("")
animal = input ("pick an animal: ")
location = input ("now pick a location: ")
print("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~")
print (f" One day, an {animal} wandard into {location}...")
print ("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~")