name = input ("What is your name?")
print (f"hello {name} and welcome to CT8")
print ("Today we will tell a story with your help")
print ("")
print ("")
animal = input ("pick an animal: ")
location = input ("Now pick a location: ")
print ("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~")
print(f"One day, a {animal} with the name of {name} wandard into a location ")
print ("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~")